name: 'example'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job 1
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - id: shorten_commit_sha
        uses: iendeavor/shorten-commit-sha@v2.0.5

      - run: |
          echo "env: ${{ env.shortened_commit_sha }}"
          echo "output: ${{ steps.shorten_commit_sha.outputs.shortened_commit_sha }}"

  job2:
    runs-on: ubuntu-latest
    name: Job 2
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - id: shorten_commit_sha
        uses: iendeavor/shorten-commit-sha@v2.0.5
        with:
          env_name: foo
          length: 8
          output_name: bar
          pull_request_github_sha: github.event.pull_request.head.sha # use the last commit to the head branch of the pull request, instead of the last merge commit of the pull request merge branch

      - run: |
          echo "env: ${{ env.foo }}"
          echo "output: ${{ steps.shorten_commit_sha.outputs.bar }}"